### ISSUE TITLE
Won't authenticate to FAKKU

### ISSUE THREAD

**Issue by shinji257** [jobobby04/Lanraragi-Fakku-Tagger#2]
Whenever I try to supply my fakku_sid it reports back that the login failed.  Same fakku_sid works with your missing galleries app.

**Comment by shinji257** [comment]
```
PS P:\git> java -jar .\LanraragiFakkuTagger-1.5.jar Etx8CFvhTJiWtc http://10.0.0.149:3000 redactedfakkusid 0 0 resetAllTags debug
[main] INFO Main - Getting lanraragi metadata plugins
[main] INFO io.ktor.client.HttpClient - REQUEST: http://10.0.0.149:3000/api/plugins/metadata
METHOD: HttpMethod(value=GET)
[DefaultDispatcher-worker-1] INFO io.ktor.client.HttpClient - RESPONSE: 200 OK
METHOD: HttpMethod(value=GET)
FROM: http://10.0.0.149:3000/api/plugins/metadata
[DefaultDispatcher-worker-1] INFO Main - Getting all lanraragi galleries
[DefaultDispatcher-worker-1] INFO io.ktor.client.HttpClient - REQUEST: http://10.0.0.149:3000/api/archives
METHOD: HttpMethod(value=GET)
[DefaultDispatcher-worker-2] INFO io.ktor.client.HttpClient - RESPONSE: 200 OK
METHOD: HttpMethod(value=GET)
FROM: http://10.0.0.149:3000/api/archives
[DefaultDispatcher-worker-2] INFO Main - Getting FAKKU page to check login status
[DefaultDispatcher-worker-2] INFO io.ktor.client.HttpClient - REQUEST: https://www.fakku.net/subscription
METHOD: HttpMethod(value=GET)
[DefaultDispatcher-worker-3] INFO io.ktor.client.HttpClient - RESPONSE: 302
METHOD: HttpMethod(value=GET)
FROM: https://www.fakku.net/subscription
[DefaultDispatcher-worker-3] INFO io.ktor.client.HttpClient - REQUEST: https://www.fakku.net/
METHOD: HttpMethod(value=GET)
[DefaultDispatcher-worker-2] INFO io.ktor.client.HttpClient - RESPONSE: 200
METHOD: HttpMethod(value=GET)
FROM: https://www.fakku.net/
[DefaultDispatcher-worker-2] INFO Main - Checking FAKKU login
[DefaultDispatcher-worker-2] INFO Main - Failed FAKKU login, retry with a new sid cookie
```

**Comment by jobobby04** [comment]
My missing galleries app does not test the cookie. Make sure your still logged in on Fakku, it likes to invalidate the cookie whenever it wants

**Comment by shinji257** [comment]
Yes but this one (that I bugged on) still does based on the commit from 8 months ago. I even copied the code block that checks.

**Comment by jobobby04** [comment]
? 
I tested the code with a valid sid cookie and it works fine for me, so unless your using a invalid sid cookie it shouldnt have problems

**Comment by shinji257** [comment]
I couldn't get it to work at the time with the same cookie on both. Just in case it is an id10t moment can you provide the command line on how you are doing it?  I'll try it later on and see what happens. 

I'll note that the cookie I'm using right now with the check Skipper works fine. I know since my login has controversial content enabled and tried it on something that would have been blocked otherwise.

**Comment by shinji257** [comment]
Yea.  Still fails with that code block in place and I don't know why it works for you but not for me.  Coming off my patched version I went and tried again with your build and I tried both with and without fakku_sid as a prefix for the cookie.  I then followed it up with using against your missing galleries script and it worked fine immediately.  Had it look at the tentacles prefix on purpose since that one is a controversial category and blocked for unauthenticated sessions.  It grabbed the pages fine.  When I removed the cookie from the command for that it failed with a 403 response.

![image](https://user-images.githubusercontent.com/261005/227834880-c10f440a-1031-4a3a-8a8c-f316e8d29e8e.png)

Debug run for reference:
![image](https://user-images.githubusercontent.com/261005/227835109-4eb798b0-c348-404e-9068-1e964a9e59ac.png)

**Comment by jobobby04** [comment]
Hmm for fakku, are you subscribed to Fakku unlimited?

**Comment by shinji257** [comment]
Yes.

**Comment by jobobby04** [comment]
That must be why, to check if the login works, I test if there is a subscribe button

**Comment by jobobby04** [comment]
If you go to https://www.fakku.net/subscription is there a big green button? If there is, can you right click it and copy the link to send it here

**Comment by shinji257** [comment]
When I go there I just get redirected to the homepage as I'm already subscribed.  This is actually indicated in the 302 (Found redirect) response in the debug output earlier.

**Comment by jobobby04** [comment]
Huh, ok. I can work with that

**Comment by jobobby04** [comment]
@shinji257 Can you try this build and give me the output if it doesnt work?
[LanraragiFakkuTagger-1.7-SNAPSHOT.zip](https://github.com/jobobby04/Lanraragi-Fakku-Tagger/files/11241073/LanraragiFakkuTagger-1.7-SNAPSHOT.zip)
