### ISSUE TITLE
Previously untagged items will end up with a "blank" tag at the start

### ISSUE THREAD

**Issue by shinji257** [jobobby04/Lanraragi-Fakku-Tagger#4]
If there are no tags already on an item then the code (asis) seems to try and prefix an empty variable for the metadata that is then comma separated.  This results in a submission of something like `,tag1,tag2,etc.`.  Lanraragi is interpreting that first comma as having an empty tag in front and renders it on the website.  This doesn't happen if at least one tag already exists.

![image](https://user-images.githubusercontent.com/261005/227699512-6dc9a840-1dbc-4000-8d93-30d6c436a47f.png)

Additionally `resetAllTags` doesn't seem to work.  I can end up with duplicate tags as a result of it bring in the old tags that still exist either in code, on the site, or both.

**Comment by jobobby04** [comment]
Fixed these in 1.6 👍
